# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aGXBrosAlUYH3g2JSEimmSfEqWVFPaGO
"""

top_side=10
bottom_side=20
height=5

area=(top_side+bottom_side)*height/2

print(str(area)+"cm²")

